server:
  port: 4004

spring:
  data:
    redis:
      ## use REDIS_HOST environment variable or use fallback 'redis'
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT;6379}
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            ## maximum number of requests allowed at once per second per IP address
            redis-rate-limiter.burstCapacity: 5
            ## how many requests are allowed to be added per second
            redis-rate-limiter.replenishRate: 5
            ## from RateLimiterConfig
            key-solver: "#{@ipKeyResolver}"

      routes:
        ## Client makes request to API Gateway: http://localhost:4004/auth/login
        ## API GATEWAY -> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1


        ## Client makes request to API Gateway: http://localhost:4004/api/patients
        ## Gateway matches the predicate /api/patients/**.
        ## Gateway applies filter strip-prefix=1 ? becomes /patients.
        ## Gateway forwards request to Patient Service: http://patient-service:4000/patients.
        - id: patient-service-route
          uri: http://patient-service:4000   #destination
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation


        ## Client calls: http://localhost:4004/api-docs/patients
        ## Gateway matches predicate /api-docs/patients.
        ## Gateway rewrites path: /api-docs/patients ? /v3/api-docs
        ## Gateway forwards to Patient Service: http://patient-service:4000/v3/api-docs
        - id: api-doc-patient-route
          uri: http://patient-service:4000   #destination
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs


        - id: api-docs-auth-route
          uri: http://auth-service:4005   #destination
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs